# Generated by Django 3.2.14 on 2022-08-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(choices=[('GO', 'I like it!'), ('NO', 'Everything need to be improved'), ('SI', 'Need style improvement'), ('FI', 'Need features improvement')], default='GO', max_length=2),
        ),
    ]
